export const burritos = [
  {
    id: '1',
    name: 'Ultimate Burrito',
    link: 'products/ultimate-burrito',
    desc: 'This is the ultimate burrito.',
    price: 33,
    img: 'placeholder',
    ingredients: {
      meat: true,
      cheese: true,
      beans: true,
      lettuce: true,
      guacamole: true,
      salsa: true,
      sourcream: true,
      tomato: true,
      coriander: true,
    },
  },
  {
    id: '2',
    name: 'Beef Burrito',
    link: 'products/beef-burrito',
    desc: 'This is an amazing beef burrito.',
    price: 23,
    img: 'placeholder',
    ingredients: {
      meat: true,
      cheese: true,
      beans: true,
      lettuce: false,
      guacamole: false,
      salsa: true,
      sourcream: true,
      tomato: false,
      coriander: false,
    },
  },
  {
    id: '3',
    name: 'Chicken Burrito',
    link: 'products/chicken-burrito',
    desc: 'This is an amazing chicken burrito.',
    price: 26,
    img: 'placeholder',
    ingredients: {
      meat: true,
      cheese: false,
      beans: true,
      lettuce: true,
      guacamole: true,
      salsa: false,
      sourcream: true,
      tomato: true,
      coriander: true,
    },
  },
  {
    id: '4',
    name: 'Bean Burrito',
    link: 'products/bean-burrito',
    desc: 'This is an amazing vegetarian bean burrito.',
    price: 28,
    img: 'placeholder',
    ingredients: {
      meat: false,
      cheese: true,
      beans: true,
      lettuce: false,
      guacamole: false,
      salsa: true,
      sourcream: false,
      tomato: false,
      coriander: true,
    },
  },
  {
    id: '5',
    name: 'Vegan Burrito',
    link: 'products/vegan-burrito',
    desc: 'This is an amazing vegan burrito.',
    price: 28,
    img: 'placeholder',
    ingredients: {
      meat: false,
      cheese: false,
      beans: true,
      lettuce: true,
      guacamole: true,
      salsa: true,
      sourcream: false,
      tomato: true,
      coriander: true,
    },
  },
];
